# Generated by Django 4.1.7 on 2023-03-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('titulli', models.CharField(max_length=150)),
                ('tekst', models.TextField(max_length=300)),
                ('foto', models.ImageField(null=True, upload_to='post')),
                ('slug', models.SlugField()),
                ('autori', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.autori')),
            ],
        ),
    ]
